Check arguments exist

diff --git a/srm b/srm
--- a/srm
+++ b/srm
@@ -4,6 +4,13 @@
 # Test cleaning
 # touch -a -m -t 201512180130.09 ~/RECYCLE/old_test_file
 
-echo 'Safe remove v.0.1'
+echo 'Safe remove v.0.1
+
+if [ $# -eq 0 ]
+  then
+    echo "srm: missing operand"
+    exit 1
+fi
+
 mkdir -p ~/RECYCLE
 find ~/RECYCLE* -mtime +7 -exec rm {} \;
